### ISSUE TITLE
Better remote module communication (bigger radius)

### ISSUE THREAD

**Issue by feldim2425** [feldim2425/OC-Minecarts#4]
The Remote Module should control locomotives from a bigger distance than 4 blocks.
The problem is that a wireless communication over more than 4 blocks without energy is a bit unbalanced.

My ideas:
- Adding a Tier 2 module that requires energy for a range more than 4 blocks.
- Adding a new block that can communicate with all modules in a big range (~ 400 blocks)
- Just allow the existing module to communicate in a bigger radius. (unbalanced)

What did you think?

**Comment by Timmy94W** [comment]
The first sounds good. maybe 3 Tiers
Tier 1: 4 Blocks
Tier 2: 64 Blocks
Tier 3: 256 Blocks

**Comment by hron84** [comment]
Just random ideas:

Idea1: make the control distance slightly bigger, e.g. 10-20 block, and every placed module can relay the signal too. 
Idea2: integrate with Immersive Engineering, make a wire and a connector to transfer info for bigger distances and an upgraded scaffold that only provides a way to connect the connector (since rails needs solid block beneath them. Steel scaffolds would be a good subject of this evolution.
Idea3: integrate with RailCraft, make a Radio cart, that has a bigger distance to catch and send controlling signals.

Also, for idea3: you should handle if the cart is not running by its own internal engine, but for example dragged by a linked locomotive...

**Comment by feldim2425** [comment]
Idea 3 should work. Maybe I will add a Radio Cart.

Problem with Idea1:  This may create dublicated messages and loops.
Problem with Idea2: Only works with IE

**Comment by hron84** [comment]
@feldim2425 Idea 3 will work only with Railcraft, since you can only link carts in this. But I agree, this could be pretty close for the theme of the mod.

**Comment by feldim2425** [comment]
I close this for now, because I already added the tiered version of the remote module (in the commits) and the new update should be ready soon.
